### ISSUE TITLE
GridEnforcer.blockRemoved marks ship as unclassified if user removes one of many

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#1]
Currently the HullClassifier removal check in `GridEnforcer.blockRemoved` doesn't check if there are additional HullClassifiers on the grid before marking it as UNCLASSIFIED.

**Comment by stackcollision** [comment]
Intentional.  If the player tries to place a classifier on an already-classified hull the new block will be deleted.  It is not possible to have two classifiers.

**Comment by zrisher** [comment]
Interesting, makes sense. If there's a bug in the add-check this would very much break, but you're right since the block is mod-dependent it couldn't just be added while the mod was off. Hadn't thought of that.
