### ISSUE TITLE
Need a way to disable or hide the CP GPS points

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#112]
Or people can't stream / upload photos without having their position triangulated.

Per Molotovsoda, this is not currently possible in game.

**Comment by zrisher** [comment]
Just looked in game, it seems temporary GPS points are handled a little differently now and no longer listed in the GPS menu, so they can't be removed there. We should add a command to toggle these on/off, i.e. `/gc cps on`, `/gc cps off`.

**Comment by HaoTNN** [comment]
I'll implement this if you're not already on it.

Looking through how IMyGpsCollection works, the only way to uniquely identity an IMyGps object is its hash value, calculated from its name and coords. We can get its hash value if we have the object to reference, or create a new IMyGps object with the same name and coords.

I'm thinking we store the GPS of the ControlPoint into a List<IMyGps> in ResponseProcessor upon getting server information. This way, we have a direct reference to it so we don't have to recreate it. From there, we can RemoveLocalGps or AddLocalGps in CommandProcessor, depending on whether the user wants it on or off.

How's that sound?

**Comment by zrisher** [comment]
Hahah wow your description is pretty much spot on to how I implemented in #113 (just a couple hours ahead of you!). If you have time to take on #99 that would be very helpful, though.

**Comment by zrisher** [comment]
Closed via #113.
