### ISSUE TITLE
HullClassifiers for Small Combat Ships

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#18]
Looking at the [youtube HW ship comparison](https://youtu.be/qG3stLXpZ2w?t=2m43s) and thinking about our sectioning needs, I'd love to have these HullClassifiers for small combat ships:
- `ScoutHullClassifier` - small ship, small number of blocks, no turrets
- `FighterHullClassifier` - small ship,  medium number of blocks, no turrets
- `CorvetteHullClassifier` -  small ship, large number of blocks, "small ship" turrets

This is a change from the current situation where fighter covers the whole spectrum - I suggest we move corvette down to the small block section and introduce scout to better segment this group. I can see Scout being particularly useful for people making missiles or other small remote-controlled craft if it was cheaper than a fighter. I can see Corvette being a really cool place to allow small-ship turrets.

See #19 for priority on this.

**Comment by stackcollision** [comment]
Corvettes are large ships in the real world.  They are also large ships in Homeworld, they just look comparable in size to the fighters because the fighter models are artificially scaled up to make them visible at all.

**Comment by zrisher** [comment]
Yeah in the HW class system I can see them being classified as "Large", but:
- the amount of detail they get into their size they seem a better fit for "Small"
- we have a lot more control if we segment "Small" combat ships into more than 1 size group
- I think small ship vs large ship turrets is a really interesting dynamic and I'd like to include it, but I can't if we only have only one class for small ships
