### ISSUE TITLE
Solo players aren't included in Faction Grid Count limits

### ISSUE THREAD

**Issue by stackcollision** [stackcollision/GardenConquest#26]
Players not in a faction can create as many Unlicensed grids as they want.

**Comment by chickenbranches** [comment]
Is it possible to disable player's ability to build anything if they are not in a faction to force them to create their own faction or join one when they first get into the game.

**Comment by stackcollision** [comment]
It is possible.  However it would piss a lot of players off.  On permadeath servers many people don't create a faction until they have an established base, because if you die with no medbay you lose your faction.

**Comment by chickenbranches** [comment]
Does it just leave a faction with no members? if so, any way to purge those factions every so often or on player death or something so they can remake the faction? If you already have a solution in the works then nevermind, just trying to help get it going. Is permadeath even needed? If the chat command to revoke a license/grid is in the game then there shouldn't be a problem with permadeath being off.

**Comment by zrisher** [comment]
SE is supposed to automatically cleanup faction and player info for people that have no grids in the world. But I have a feeling it doesn't do it very well - time will tell once we have conquest doing the ship cleanup.

**Comment by zrisher** [comment]
Closed via #58 and previous work from stackcollision
