### ISSUE TITLE
HullClassifiers for Stations

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#3]
We could use some classes of stations - these are generally much cheaper on performance than ships of the same size. Providing classes for their different tiers would really augment the flexibility of our block control scheme. Perhaps (temporary numbers):

<50 Platform
<150 Outpost
<500 Station
<1500 Installation

Something like that, definitely not married to the names.

**Comment by stackcollision** [comment]
I thought about a station-specific beacon, but the problem is that large grids can be converted between stations and ships almost at will.

**Comment by zrisher** [comment]
I believe you have to own a large % of the functional blocks on the grid to change it from station<->ship, just like the naming it. 

If the worry is someone would try to grief your ship/station by changing its type and then forcing a Conquest cleanup, it seems much harder to do this than it would be to simply find the grid's license block and remove it.

**Comment by stackcollision** [comment]
Nope, anyone can do it.  We do it all the time when we raid bases.  Whatever we can't steal we convert to a ship and override the thrusters and gyros.

I'm raising the objection because there's no functional difference between the current ship classifiers and the station classifiers you're proposing.

**Comment by zrisher** [comment]
Totally understand, the functional difference would be that Station classifiers would be a lot cheaper. There are reports that a lot of production activities (refining, assembling, but especially using a projector) are much less CPU-intensive on a stationary platform than a ship. But physics calculations are definitely easier on a stationary object.

**Comment by stackcollision** [comment]
So would you say that large grids with these station beacons would be immobile permanently?  Lots of players convert their stations to ships to escape enemies, or to move their base around.  I also don't know if there's a way to prevent a player from converting a grid to a ship.

**Comment by zrisher** [comment]
I'm fine with them doing it infrequently, I'd just like it to be a station "most of the time." If we have a bit of leeway on the timing of enforcement, it's ok for someone to take a station, convert it to a ship, fly it somewhere else real fast and convert it back. It that enforcement leeway is small enough that they'd need to convert it back before leaving for the day, that should be sufficient.

I also bring this up because we're going to want to limit medbays as much as possible, and keeping them mostly on stations (and big capital ships) is a good way to do that. If a ship doesn't have a medbay I can use DynamicConceal on it, which almost entirely negates the performance cost of that grid. If it does have a medbay, I don't want to conceal it bc someone may want to spawn there.

**Comment by zrisher** [comment]
See #19 for priority.

**Comment by zrisher** [comment]
This is now implemented and in process.
