### ISSUE TITLE
Add conquest to player GPS if not in their list

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#36]
Should we attempt to add the conquest GPS coords to player lists for them? Or provide it as an option via one of the chat commands?

I've heard adding these was recently enabled, but deleting them is not yet possible.

**Comment by chickenbranches** [comment]
The last server I played one, whenever someone posted a gps in chat, it would show up in everyone's gps tab and would only save for the player if they click to show on hud. I don't know if this was done through one of their mods or what.

**Comment by zrisher** [comment]
There's a method to add GPS points to player lists directly through the modapi now. And if there's not a way to remove them... I can submit a PR to core for that.

This wouldn't make use of chat at all.

**Comment by zrisher** [comment]
Gniiiiiice
