### ISSUE TITLE
slowly destroy Derelicts

### ISSUE THREAD

**Issue by zrisher** [stackcollision/GardenConquest#4]
We should turn Unclassified grids into Derelicts after X hours and slowly destroy them.

**Comment by stackcollision** [comment]
This is already in the works but uncommitted.

I was thinking of starting a timer on unclassified hulls (say, 3 hours), and if they are not classified in that time all of their terminal blocks will be damaged below their functional threshold in one fell swoop.

**Comment by zrisher** [comment]
Regarding the cleanup logic, damaging terminal blocks helps but wouldn't be optimal. There are many simply functional blocks that cause lag, as well as non-functional blocks (i.e. interior walls). Also, damaged blocks take up a lot more system resources than undamaged ones. Plus, even if everything is off, the ship could be moving and taking up resources. I'd suggest the following progression over time, similar to my proposed logic for Derelicts:
- stop the ship and turn everything off (at first, and every time the cleanup is run)
- remove some of the high-cpu blocks like projectors and turrets
- once that's done, remove some of the mid-cpu blocks like timers, programmable blocks, lights, refineries, assemblers, and damaged blocks
- once that's done, remove some of anything else besides armor
- incrementally remove armor

Alternatively, or as a stopgap, you could:
- stop the ship and turn everything off immediately
- remove everything after 3 hours

**Comment by stackcollision** [comment]
This is do-able.  However I would prefer to not stop the ship, I think it will kill the atmosphere just to have it stop dead in its track.  Also I know lots of people who prefer to kill ships by sending them off into deep space.

The complicated removal process you described is something I would like to do at some point in the future, but maybe not in the first release.

**Comment by zrisher** [comment]
Yeah I understand not wanting to stop the ship for atmospheric reasons, but maybe that should be tempered with a understanding of the number of unclassified ships on the map. Sure, if you lose classification on one thing it'd be cool to see it drift away unpowered. But if you're in a major battle and all of a sudden there's 50 grid parts all swirling around madly in circles and jetting off in various directions, stopping those could be the difference between 1.0 Sim and 0.1.

**Comment by zrisher** [comment]
So FYI I see this is now built to remove all functional blocks when a ship becomes a Derelict after X hours. For the beta implementation, I would love to get two additional things:
- stop the ship if there are more than X derelicts on the map or simply after another timer runs out
- start another timer to remove the ship entirely farther down the road, maybe a few days. It's great that that's possible now with persistent timers.

**Comment by zrisher** [comment]
Besides the first post, this thread is entirely about Dereliction so I'm renaming and re-opening the original subject.
